---
  - name: ans_06
    hosts: stage_1
    pre_tasks:
     - raw: apt-get install -y python-simplejson
    roles: 
      - role: nginx_deploy
        tags: nginx
      - role: letsencrypt_pre
        tags: li
      - role: letsencrypt_cert
        tags: srt
      - role: vhost_deploy
        tags: vhost
      
    
 
       
        
     
     
       
    