---
# tasks file for letsencrypt_pre
 - name: install letsencrypt
   apt:
    name: letsencrypt
    update_cache: yes 
    state: latest

 - name: create letsencrypt directory
   file: 
       path: "/var/www/letsencrypt"
       state: directory
       mode: '0755'
  
 - name: Install nginx site for letsencrypt requests
   template:
        src: letsencrypt_answer.j2
        dest: "{{ enabled }}/ssl_challange.conf"
        mode: "644"
   with_items:
      -  { server_name: "{{ server_name[0] }}" }
   notify: 
     - Reload service nginx      
 - name: Force reload nginx
   meta: flush_handlers  