---
# tasks file for nginx_deploy
  - name: Install package nginx
    apt: 
       name: nginx=1.14.0-0ubuntu1.9
       update_cache: yes 
       state: present
    notify:  
       - Starting service nginx

  - name: copy nginx.conf
    copy: 
       src: "nginx.conf"
       dest: "/etc/nginx"
    notify:  
       - Reload service nginx
  - name: Remove default nginx config
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent    
    notify:  
       - Reload service nginx    
  